### ISSUE TITLE
Can't get object by id

### ISSUE THREAD

**Issue by clenk** [freetaxii/freetaxii-server#4]
It seems that new STIX objects are created every time the objects endpoint is queried. Every time I request it, the id/created/modified properties of all the objects are different. This makes it very hard to get an object by its id.

**Comment by johnwunder** [comment]
We were just talking about this in a team meeting and the other behavior is that if you ask for an object by ID, it isn't able to find an object with that ID (of course) but instead of returning a 404 for that object it just returns all objects. Seems like the behavior should be that if an ID isn't found, you get a 404.

**Comment by jordan2175** [comment]
I have added support for getting an object by ID.  I still have some work to do with getting the right error codes sent back when the object is not found, but you can at least get an object by ID now.

**Comment by jordan2175** [comment]
This has now been fixed and the server gives not only an HTTP error code correctly, but also gives a TAXII Error message.
